### ISSUE TITLE
API research Yahoo

### ISSUE THREAD

**Issue by SLDem** [Lv-581-Python-project/StockDashboard#3]
1. https://pypi.org/project/yfinance/

**Comment by mariob0y** [comment]
Pros: 
 * Free and unlimited use
 * Simple use and install 
 * High granularity of data (1min/2min/5min data)
 * Returns data directly in pandas dataframes/series 

Cons: 
 * Unofficial origin - no warranty of any kind
 * Rather limited documentation
 https://pypi.org/project/yfinance/
